Repository atlp-rwanda/e-commerce-ninjas-bn, pull requests merged in 2024-06, with the labels that each got.

#47 Ft login v google 187584916
  .env.example
  .github/workflows/ci.yml
  .nycrc
  README.md
  package-lock.json
  package.json
  src/databases/migrations/20240520180022-create-users.ts
  src/databases/models/users.ts
  src/modules/auth/test/auth.spec.ts
  src/routes/authRouter.ts
  src/services/googleAuth.ts
  src/types/index.d.ts
  swagger.json
Labels: Ready

#63 ft-view-specific-item
  README.md
  src/databases/seeders/20240607133118-cartProducts.ts
  src/middlewares/validation.ts
  src/modules/cart/test/cart.spec.ts
  src/modules/product/controller/productController.ts
  src/modules/product/repositories/productRepositories.ts
  src/modules/product/test/product.spec.ts
  src/routes/index.ts
  src/routes/productRouter.ts
  swagger.json
Labels: Ready

#70 [starts #187584933] Add & Update cart
  README.md
  src/enums/index.ts
  src/middlewares/validation.ts
  src/modules/cart/controller/cartControllers.ts
  src/modules/cart/repositories/cartRepositories.ts
  src/modules/cart/test/cart.spec.ts
  src/modules/cart/validation/cartValidations.ts
  src/routes/cartRouter.ts
  swagger.json
Labels: ready-to-be-merged

#67 Users should be able to chat on the App to ask some information publicly
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/databases/migrations/20240611220815-create-chat.ts
  src/databases/models/chats.ts
  src/databases/models/index.ts
  src/databases/seeders/20240520202759-users.ts
  src/databases/seeders/20240602133044-carts.ts
  src/databases/seeders/20240607133118-cartProducts.ts
  src/helpers/index.ts
  src/index.spec.ts
  src/index.ts
  src/middlewares/authorization.ts
  src/modules/product/repositories/productRepositories.ts
  src/modules/user/controller/userControllers.ts
  src/modules/user/repository/userRepositories.ts
  src/modules/user/test/user.spec.ts
  src/routes/userRouter.ts
  src/services/chat.ts
  src/types/index.d.ts
  src/types/uuid.ts
  swagger.json
Labels: ready-to-be-merged

#71 ft buyer add product to wishList
  README.md
  package.json
  src/databases/migrations/20240617170923-create-wishLists.ts
  src/databases/models/index.ts
  src/databases/models/wishLists.ts
  src/databases/seeders/20240617174202-wishLists.ts
  src/middlewares/validation.ts
  src/modules/product/controller/productController.ts
  src/modules/product/repositories/productRepositories.ts
  src/modules/product/test/product.spec.ts
  src/routes/productRouter.ts
  src/types/uuid.ts
  swagger.json
Labels: Ready

#75 Ft clear wish list
  README.md
  src/middlewares/validation.ts
  src/modules/product/controller/productController.ts
  src/modules/product/repositories/productRepositories.ts
  src/modules/product/test/product.spec.ts
  src/routes/productRouter.ts
  swagger.json
Labels: Ready

#66 Ft buyer clear cart 187584935
  README.md
  package-lock.json
  package.json
  src/middlewares/validation.ts
  src/modules/cart/controller/cartControllers.ts
  src/modules/cart/repositories/cartRepositories.ts
  src/modules/cart/test/cart.spec.ts
  src/modules/product/controller/productController.ts
  src/modules/product/repositories/productRepositories.ts
  src/modules/product/test/product.spec.ts
  src/routes/cartRouter.ts
  src/routes/productRouter.ts
  src/types/index.d.ts
  swagger.json
Labels: Ready

#77 [Delivers-18758493] ft-buyer-checkout
  src/middlewares/validation.ts
  src/modules/cart/controller/cartControllers.ts
  src/modules/cart/repositories/cartRepositories.ts
  src/modules/cart/test/cart.spec.ts
  src/routes/cartRouter.ts
  src/types/index.d.ts
  swagger.json
Labels: Ready

#82 [Deliver-18758493] ft-fix-checkout
  src/modules/cart/controller/cartControllers.ts
  src/modules/cart/repositories/cartRepositories.ts
  src/modules/cart/test/cart.spec.ts
Labels: reviewing
